default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ramenman_development

test:
  <<: *default
  database: ramenman_test

production:
  <<: *default
  database: ramenman_production
  username: ramenman
  password: <%= ENV['RAMENMAN_DATABASE_PASSWORD'] %>
