# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 22f361c7eaa217866796fd100144b756d6d6ba8f43532f85cd4dc528fa6b55a94b2a9042149f6a775d870c56f97f13e8eb7de49d416fea6be4bec79c0f66c621

test:
  secret_key_base: 51bd34b855612d181c39ba87172ad9c873adcb2ec0d627ddce09b3c1c0f6e4638286d6f06884964047ed807d25d7d0e433933f0c61f48cdaa9febfa397311914

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
